### PR TITLE
[v2] Offchain integrations with v2 contracts

### PR DESCRIPTION
**Pull request by ian-shim**
## Why are these changes needed?
Bindings + client methods to get latest blob version and relay key

## Checks

- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, in that case, please comment that they are not relevant.
- [ ] I've checked the new test coverage and the coverage percentage didn't drop.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Integration tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by cody-littley — APPROVED** [review]
Not a blocker, more of a process question.

I'm always a bit suspicious of automatically generated code that we manually have to update. Would it be plausible (as a future change) to ensure that the bindings are automatically generated? We could perhaps use a CI pipeline strategy similar to how we currently enforce that the proto files get properly generated.

**Review by jianoaix — APPROVED** [review]

**Comment by ian-shim** [comment]
> Not a blocker, more of a process question.
> 
> I'm always a bit suspicious of automatically generated code that we manually have to update. Would it be plausible (as a future change) to ensure that the bindings are automatically generated? We could perhaps use a CI pipeline strategy similar to how we currently enforce that the proto files get properly generated.

I agree. Right now, given that offchain codebase directly imports the bindings, it would be very risky to automatically generate the bindings following contract updates. So I think bindings should be generated/integrated manually at this point. 

imo, the right way to deal with this is to have a separate repo for contracts. This would allow contract development to make progress independently with separate release process, and offchain code can update dependency whenever it's ready. Then we can have bindings autogenerated in the contracts repo

**Comment by jianoaix** [comment]
> > Not a blocker, more of a process question.
> > I'm always a bit suspicious of automatically generated code that we manually have to update. Would it be plausible (as a future change) to ensure that the bindings are automatically generated? We could perhaps use a CI pipeline strategy similar to how we currently enforce that the proto files get properly generated.
> 
> I agree. Right now, given that offchain codebase directly imports the bindings, it would be very risky to automatically generate the bindings following contract updates. So I think bindings should be generated/integrated manually at this point.
> 
Any examples of this risk?

> imo, the right way to deal with this is to have a separate repo for contracts. This would allow contract development to make progress independently with separate release process, and offchain code can update dependency whenever it's ready. Then we can have bindings autogenerated in the contracts repo

**Comment by ian-shim** [comment]
> Any examples of this risk?

If we generate bindings automatically on contract changes without corresponding offchain updates, offchain code ends up importing the new bindings which may be no longer compatible

**Review by pschork — APPROVED** [review]

**Pull request merged**
