### PR TITLE
[DataApi] Update endpts to spinal-case

### PR DESCRIPTION
**Pull request by siddimore**
## Why are these changes needed?
Define URI as spinal-case to make it compliant with RFC3986

## Checks

- [ ] I've made sure the lint is passing in this PR.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, in that case, please comment that they are not relevant.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Integration tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by dmanc — CHANGES_REQUESTED** [review]
This would break the blob explorer. We would need to introduce new APIs, onboard the frontend, and then deprecate the old ones.

**Comment by dmanc** [comment]
> This would break the blob explorer. We would need to introduce new APIs, onboard the frontend, and then deprecate the old ones.

Actually maybe not, @QuinnLee do you use any of these endpoints?

**Comment by jianoaix** [comment]
The blob explorer does. A safe way is to add new endpoint (with intended URI format), change frontend to use new endpoint, and then remove the old one.

**Review by QuinnLee — APPROVED** [review]

**Comment by QuinnLee** [comment]
approved, the blob explorer doesnt use any of these endpoints so it's safe to merge and ship

**Review by jianoaix — APPROVED** [review]

**Review by dmanc — APPROVED** [review]

**Pull request merged**
