### PR TITLE
Use logfmt instead of terminal format

### PR DESCRIPTION
**Pull request by dmanc**
## Why are these changes needed?

Right now our logs look like this:
```
INFO [01-30|15:23:34.705|github.com/Layr-Labs/eigenda/disperser/dataapi/server.go:514] server running                           addr=:8080 caller=server.go:514
```
This is because we use "Terminal Format" which should really only be used in development.

Grafana will have an easier time parsing the log if we use [logfmt (brandur.org)](https://www.brandur.org/logfmt):
```
t=2024-01-30T15:25:39-0800 lvl=dbug msg="Getting blob metadata"               batchHeaderHash="[48 120 51 50 54 54 101 54 57 50 102 97 98 101 97 57 102 57 102 55 51 52 51 99 98 101 49 97 97 57 53 100 97 52 56 57 98 54 52 99 101 53 53 49 97 53 56 54 55 52 102 51 48 101 55 48 54 98 100 102 48 99 48 57 98 99]" caller=server.go:425
```

## Checks

- [ ] I've made sure the lint is passing in this PR.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, in that case, please comment that they are not relevant.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Integration tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by jianoaix — APPROVED** [review]

**Review by ian-shim — APPROVED** [review]

**Comment by jianoaix** [comment]
We have a use case for terminal log: the nodeplugin used by the operators. May need to check the output there to make sure   it's good.

**Comment by dmanc** [comment]
> We have a use case for terminal log: the nodeplugin used by the operators. May need to check the output there to make sure it's good.

Good point, what do you think about making the format a config flag?

**Comment by jianoaix** [comment]
> > We have a use case for terminal log: the nodeplugin used by the operators. May need to check the output there to make sure it's good.
> 
> Good point, what do you think about making the format a config flag and make current behavior the default?

SG

**Review by shrimalmadhur — APPROVED** [review]
LGTM - we should work on using single log framework across repos.

**Pull request merged**
