### PR TITLE
improve: use errors.New to replace fmt.Errorf with no parameters

### PR DESCRIPTION
**Pull request by 0x2d3c**
Parameterless errors should be using errors.New instead of fmt.Errorf

### CODE REVIEW

**Comment by jianoaix** [comment]
Can you review the repo and make sure all are fixed the same way like this?

**Comment by 0x2d3c** [comment]
> Can you review the repo and make sure all are fixed the same way like this?

Thanks for your suggestion, the rest has been taken care of.

**Comment by jianoaix** [comment]
Thanks, please merge master and resolve the conflicts.

**Comment by 0x2d3c** [comment]
> Thanks, please merge master and resolve the conflicts.

I'll try it again

**Pull request closed without merging**
