### PR TITLE
improve: use errors.New to replace fmt.Errorf with no parameters

### PR DESCRIPTION
**Pull request by 0x2d3c**
errors.New to replace fmt.Errorf with no parameters shuld match better

In order to solve the error in https://github.com/Layr-Labs/eigenda/pull/290 , this PR has been added

### CODE REVIEW

**Comment by jianoaix** [comment]
can you add back your original PR description here so the context of why this PR is needed is more clear

**Comment by 0x2d3c** [comment]
In order to solve the error in #290 , this PR has been added

**Comment by 0x2d3c** [comment]
> can you add back your original PR description here so the context of why this PR is needed is more clear

Thanks again for your guidance

**Comment by jianoaix** [comment]
> In order to solve the error in #290 , this PR has been added

Can you put it in PR description section above? Like why `errors.New()` is preferred.

btw this PR needs to resolve conflict again now, thanks for being patient

**Comment by 0x2d3c** [comment]
> > In order to solve the error in #290 , this PR has been added
> 
> Can you put it in PR description section above? Like why `errors.New()` is preferred.
> 
> btw this PR needs to resolve conflict again now, thanks for being patient

fixed

**Review by jianoaix — APPROVED** [review]

**Pull request merged**
