### PR TITLE
Uncapitalize error strings

### PR DESCRIPTION
**Pull request by estensen**
## Why are these changes needed?

> Error strings should not be capitalized (unless beginning with proper nouns or acronyms) or end with punctuation, since they are usually printed following other context. 
https://staticcheck.dev/docs/checks/#ST1005

Found with `staticcheck ./...`

## Checks

- [ ] I've made sure the lint is passing in this PR.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, in that case, please comment that they are not relevant.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Integration tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by jianoaix — COMMENTED** [review]
Hi @estensen, thanks for contributing! 

The fix looks good. I'm letting it run CI before merging it.

**Comment by ian-shim** [comment]
+1
Few tests need updates as they were matching the previous error strings

**Comment by jianoaix** [comment]
@estensen can you merge master? The test should have been fixed by https://github.com/Layr-Labs/eigenda/pull/50#event-11000080055

**Comment by estensen** [comment]
Rebased on master

**Comment by estensen** [comment]
I still have issues with creating S3 bucket timing out when running locally

```
2023/11/18 10:56:58 Current Working Directory: /Users/estensen/Developer/eigenda/inabox
Creating S3 bucket
Creating S3 bucket
Creating S3 bucket
Creating S3 bucket
Creating S3 bucket
Creating S3 bucket
Could not connect to docker: reached retry deadline: exit status 127:
panic: failed to deploy AWS resources

goroutine 1 [running]:
github.com/Layr-Labs/eigenda/disperser/apiserver_test.setup(0x100013c65?)
	/Users/estensen/Developer/eigenda/disperser/apiserver/server_test.go:303 +0x17e
github.com/Layr-Labs/eigenda/disperser/apiserver_test.TestMain(0x10007489a?)
	/Users/estensen/Developer/eigenda/disperser/apiserver/server_test.go:49 +0x18
main.main()
	_testmain.go:61 +0x1c6
FAIL	github.com/Layr-Labs/eigenda/disperser/apiserver	7.284s
```

**Pull request merged**
